import type { ETFInfo } from './types';

export const ETF_LIST: ETFInfo[] = [
  { ticker: 'AGQ', name: 'ProShares Ultra Silver', leverage: '2x', underlying: 'Silver' },
  { ticker: 'BNKU', name: 'MicroSectors Banks 3X', leverage: '3x', underlying: 'Banks' },
  { ticker: 'BOIL', name: 'ProShares Ultra DJ-AIG Natural Gas', leverage: '2x', underlying: 'Natural Gas' },
  { ticker: 'BULZ', name: 'MicroSectors FANG & Innovation 3X', leverage: '3x', underlying: 'Tech/FANG' },
  { ticker: 'CURE', name: 'Direxion Healthcare Bull 3X', leverage: '3x', underlying: 'Healthcare' },
  { ticker: 'CWEB', name: 'Direxion China Internet Bull 2X', leverage: '2x', underlying: 'China Internet' },
  { ticker: 'DDM', name: 'ProShares Ultra Dow 30', leverage: '2x', underlying: 'Dow Jones' },
  { ticker: 'DFEN', name: 'Direxion Aerospace & Defense 3X', leverage: '3x', underlying: 'Aerospace/Defense' },
  { ticker: 'DIG', name: 'ProShares Ultra Oil & Gas', leverage: '2x', underlying: 'Oil & Gas' },
  { ticker: 'DPST', name: 'Direxion Regional Banks Bull 3X', leverage: '3x', underlying: 'Regional Banks' },
  { ticker: 'ERX', name: 'Direxion Energy Bull 2X', leverage: '2x', underlying: 'Energy' },
  { ticker: 'FAS', name: 'Direxion Financial Bull 3X', leverage: '3x', underlying: 'Financials' },
  { ticker: 'FNGU', name: 'MicroSectors FANG+ 3X', leverage: '3x', underlying: 'FANG+' },
  { ticker: 'GDXU', name: 'ProShares Ultra Gold Miners', leverage: '3x', underlying: 'Gold Miners' },
  { ticker: 'GUSH', name: 'Direxion Oil & Gas Bull 2X', leverage: '2x', underlying: 'Oil & Gas E&P' },
  { ticker: 'HIBL', name: 'Direxion S&P 500 High Beta Bull 3X', leverage: '3x', underlying: 'S&P High Beta' },
  { ticker: 'INDL', name: 'Direxion MSCI India Bull 2X', leverage: '2x', underlying: 'India' },
  { ticker: 'LABU', name: 'Direxion Biotech Bull 3X', leverage: '3x', underlying: 'Biotech' },
  { ticker: 'MIDU', name: 'Direxion Mid Cap Bull 3X', leverage: '3x', underlying: 'Mid Cap' },
  { ticker: 'NAIL', name: 'Direxion Homebuilders Bull 3X', leverage: '3x', underlying: 'Homebuilders' },
  { ticker: 'NRGU', name: 'MicroSectors Energy 3X', leverage: '3x', underlying: 'Energy' },
  { ticker: 'NUGT', name: 'Direxion Gold Miners Bull 2X', leverage: '2x', underlying: 'Gold Miners' },
  { ticker: 'OILU', name: 'MicroSectors Oil & Gas 3X', leverage: '3x', underlying: 'Oil & Gas' },
  { ticker: 'PILL', name: 'Direxion Pharmaceuticals Bull 3X', leverage: '3x', underlying: 'Pharmaceuticals' },
  { ticker: 'QLD', name: 'ProShares Ultra QQQ', leverage: '2x', underlying: 'NASDAQ-100' },
  { ticker: 'RETL', name: 'Direxion Retail Bull 3X', leverage: '3x', underlying: 'Retail' },
  { ticker: 'ROM', name: 'ProShares Ultra Technology', leverage: '2x', underlying: 'Technology' },
  { ticker: 'RXL', name: 'ProShares Ultra Health Care', leverage: '2x', underlying: 'Healthcare' },
  { ticker: 'SOXL', name: 'Direxion Semiconductor Bull 3X', leverage: '3x', underlying: 'Semiconductors' },
  { ticker: 'SSO', name: 'ProShares Ultra S&P 500', leverage: '2x', underlying: 'S&P 500' },
  { ticker: 'TECL', name: 'Direxion Tech Bull 3X', leverage: '3x', underlying: 'Technology' },
  { ticker: 'TNA', name: 'Direxion Small Cap Bull 3X', leverage: '3x', underlying: 'Russell 2000' },
  { ticker: 'TPOR', name: 'Direxion Transportation Bull 3X', leverage: '3x', underlying: 'Transportation' },
  { ticker: 'TQQQ', name: 'ProShares UltraPro QQQ', leverage: '3x', underlying: 'NASDAQ-100' },
  { ticker: 'UCO', name: 'ProShares Ultra Bloomberg Crude Oil', leverage: '2x', underlying: 'Crude Oil' },
  { ticker: 'UDOW', name: 'ProShares UltraPro Dow 30', leverage: '3x', underlying: 'Dow Jones' },
  { ticker: 'UGL', name: 'ProShares Ultra Gold', leverage: '2x', underlying: 'Gold' },
  { ticker: 'UPRO', name: 'ProShares UltraPro S&P 500', leverage: '3x', underlying: 'S&P 500' },
  { ticker: 'UTSL', name: 'Direxion Utilities Bull 3X', leverage: '3x', underlying: 'Utilities' },
  { ticker: 'UWM', name: 'ProShares Ultra Russell 2000', leverage: '2x', underlying: 'Russell 2000' },
  { ticker: 'UYG', name: 'ProShares Ultra Financials', leverage: '2x', underlying: 'Financials' },
  { ticker: 'WANT', name: 'Direxion Consumer Discretionary Bull 3X', leverage: '3x', underlying: 'Consumer Discretionary' },
  { ticker: 'WEBL', name: 'Direxion Dow Jones Internet Bull 3X', leverage: '3x', underlying: 'Internet' },
  { ticker: 'YINN', name: 'Direxion FTSE China Bull 3X', leverage: '3x', underlying: 'China' },
];
